// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm6BEQlMbT8hpZiMUfcjQu7NT-asLd_6k',
    appId: '1:469840950956:web:0b0645851ad40396d89109',
    messagingSenderId: '469840950956',
    projectId: 'mind-95221',
    authDomain: 'mind-95221.firebaseapp.com',
    storageBucket: 'mind-95221.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeXc4ApQ9Bukd_abbPX7B5hoWYUFmrrh4',
    appId: '1:469840950956:android:24060588b343d267d89109',
    messagingSenderId: '469840950956',
    projectId: 'mind-95221',
    storageBucket: 'mind-95221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpJr7DgKckizgo38FGO-J6sOBAxn7FGPA',
    appId: '1:469840950956:ios:71cb56600add4c74d89109',
    messagingSenderId: '469840950956',
    projectId: 'mind-95221',
    storageBucket: 'mind-95221.appspot.com',
    iosBundleId: 'com.example.mindnetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpJr7DgKckizgo38FGO-J6sOBAxn7FGPA',
    appId: '1:469840950956:ios:34f42ba080a005b9d89109',
    messagingSenderId: '469840950956',
    projectId: 'mind-95221',
    storageBucket: 'mind-95221.appspot.com',
    iosBundleId: 'com.example.mindnetwork.RunnerTests',
  );
}
